module StandardTypes
  STANDARD_TYPES = %w[ 
    AcceptedEventRelation
    Account
    AccountContactRole
    AccountFeed
    AccountHistory
    AccountOwnerSharingRule
    AccountPartner
    AccountShare
    AccountTag
    AccountTeamMember
    AccountTerritoryAssignmentRule
    AccountTerritoryAssignmentRuleItem
    AccountTerritorySharingRule
    ActionLinkGroupTemplate
    ActionLinkTemplate
    ActivityHistory
    AdditionalNumber
    AgentWork
    AllowedEmailDomain
    ApexClass
    ApexComponent
    ApexLog
    ApexPage
    ApexTestQueueItem
    ApexTestResult
    ApexTestSuite
    ApexTrigger
    Approval
    Article Type__DataCategorySelection
    Article Type__Feed
    Asset
    AssetFeed
    AssetOwnerSharingRule
    AssetShare
    AssetTag
    AssignmentRule
    AsyncApexJob
    AttachedContentDocument
    AttachedContentNote
    Attachment
    AuraDefinition
    AuraDefinitionBundle
    AuthConfig
    AuthConfigProviders
    AuthProvider
    AuthSession
    Bookmark
    BrandTemplate
    BusinessHours
    BusinessProcess
    CallCenter
    Campaign
    CampaignFeed
    CampaignMember
    CampaignMemberStatus
    CampaignOwnerSharingRule
    CampaignShare
    CampaignTag
    Case
    CaseArticle
    CaseComment
    CaseContactRole
    CaseFeed
    CaseHistory
    CaseMilestone
    CaseOwnerSharingRule
    CaseShare
    CaseSolution
    CaseStatus
    CaseTag
    CaseTeamMember
    CaseTeamRole
    CaseTeamTemplate
    CaseTeamTemplateMember
    CaseTeamTemplateRecord
    CategoryData
    CategoryNode
    CategoryNodeLocalization
    ChatterActivity
    ChatterAnswersActivity
    ChatterAnswersReputationLevel
    ChatterConversation
    ChatterConversationMember
    ChatterMessage
    CollaborationGroup
    CollaborationGroupFeed
    CollaborationGroupMember
    CollaborationGroupMemberRequest
    CollaborationGroupRecord
    CollaborationInvitation
    CombinedAttachment
    Community (Zone)
    ConnectedApplication
    Contact
    ContactFeed
    ContactHistory
    ContactOwnerSharingRule
    ContactShare
    ContactTag
    ContentDocument
    ContentDocumentFeed
    ContentDocumentHistory
    ContentDocumentLink
    ContentFolder
    ContentFolderLink
    ContentFolderMember
    ContentHubItem
    ContentHubRepository
    ContentNote
    ContentVersion
    ContentVersionHistory
    ContentWorkspace
    ContentWorkspaceDoc
    Contract
    ContractContactRole
    ContractFeed
    ContractHistory
    ContractLineItem
    ContractLineItemHistory
    ContractStatus
    ContractTag
    CronTrigger
    CronJobDetail
    CurrencyType
    CustomBrand
    CustomBrandAsset
    Custom Metadata Type__mdt
    Custom Object__Feed
    CustomPermission
    CustomPermissionDependency
    DandBCompany
    Dashboard
    DashboardComponent
    DashboardComponentFeed
    DashboardFeed
    DashboardTag
    DatacloudCompany
    DatacloudContact
    DatacloudDandBCompany
    DatacloudOwnedEntity
    DatacloudPurchaseUsage
    DatacloudSocialHandle
    DatedConversionRate
    DcSocialProfile
    DcSocialProfileHandle
    DeclinedEventRelation
    Division
    DivisionLocalization
    Document
    DocumentAttachmentMap
    DocumentTag
    DuplicateRecordItem
    DuplicateRecordSet
    EmailDomainKey
    EmailMessage
    EmailServicesAddress
    EmailServicesFunction
    EmailStatus
    EmailTemplate
    Entitlement
    EntitlementContact
    EntitlementFeed
    EntitlementHistory
    EntitlementTemplate
    EntityHistory
    EntitySubscription
    EnvironmentHubMember
    Event
    EventFeed
    EventRelation
    EventTag
    EventWhoRelation
    ExternalDataSource
    ExternalDataUserAuth
    FeedAttachment
    FeedComment
    FeedItem
    FeedLike
    FeedPollChoice
    FeedPollVote
    FeedPost
    FeedTrackedChange
    FieldPermissions
    FiscalYearSettings
    FlexQueueItem
    FlowInterview
    Folder
    ForecastingAdjustment
    ForecastingFact
    ForecastingItem
    ForecastingOwnerAdjustment
    ForecastingQuota
    ForecastingType
    ForecastShare
    Goal
    GoalFeed
    GoalHistory
    GoalLink
    GoalShare
    Group
    GroupMember
    HashtagDefinition
    Holiday
    Idea
    IdeaComment
    IdeaTheme
    KnowledgeableUser
    KnowledgeArticle
    KnowledgeArticleVersion
    KnowledgeArticleVersionHistory
    KnowledgeArticleViewStat
    KnowledgeArticleVoteStat
    Lead
    LeadFeed
    LeadHistory
    LeadOwnerSharingRule
    LeadShare
    LeadStatus
    LeadTag
    LimitAllocationPerApp
    LineitemOverride
    ListView
    ListViewChart
    ListViewChartInstance
    LiveAgentSession
    LiveAgentSessionHistory
    LiveAgentSessionOwnerSharingRule
    LiveAgentSessionShare
    LiveChatBlockingRule
    LiveChatButton
    LiveChatButtonDeployment
    LiveChatButtonSkill
    LiveChatDeployment
    LiveChatSensitiveDataRule
    LiveChatTranscript
    LiveChatTranscriptEvent
    LiveChatTranscriptHistory
    LiveChatTranscriptOwnerSharingRule
    LiveChatTranscriptShare
    LiveChatTranscriptSkill
    LiveChatUserConfig
    LiveChatUserConfigProfile
    LiveChatUserConfigUser
    LiveChatVisitor
    LoginHistory
    LookedUpFromActivity
    MacroInstruction
    MailmergeTemplate
    MatchingRule
    MatchingRuleItem
    Metric
    MetricDataLink
    MetricDataLinkHistory
    MetricFeed
    MetricHistory
    MetricShare
    MilestoneType
    Name
    NamedCredential
    NavigationLinkSet
    NavigationMenuItem
    NavigationMenuItemLocalization
    Network
    NetworkActivityAudit
    NetworkMember
    NetworkMemberGroup
    NetworkModeration
    NetworkPageOverride
    NetworkSelfRegistration
    NewsFeed
    Note
    NoteAndAttachment
    NoteTag
    OauthToken
    ObjectPermissions
    ObjectTerritory2AssignmentRule
    ObjectTerritory2AssignmentRuleItem
    ObjectTerritory2Association
    OpenActivity
    Opportunity
    OpportunityCompetitor
    OpportunityContactRole
    OpportunityFeed
    OpportunityFieldHistory
    OpportunityHistory
    OpportunityLineItem
    OpportunityLineItemSchedule
    OpportunityOverride
    OpportunityOwnerSharingRule
    OpportunityPartner
    OpportunityShare
    OpportunitySplit
    OpportunitySplitType
    OpportunityStage
    OpportunityTag
    OpportunityTeamMember
    Order
    OrderFeed
    OrderHistory
    OrderItem
    OrderItemFeed
    OrderItemHistory
    Organization
    OrgWideEmailAddress
    OwnedContentDocument
    PackageLicense
    Partner
    PartnerNetworkConnection
    PartnerNetworkRecordConnection
    PartnerNetworkSyncLog
    PartnerRole
    Period
    PermissionSet
    PermissionSetAssignment
    PlatformAction
    Pricebook2
    Pricebook2History
    PricebookEntry
    ProcessDefinition
    ProcessInstance
    ProcessInstanceHistory
    ProcessInstanceNode
    ProcessInstanceStep
    ProcessInstanceWorkitem
    ProcessNode
    Product2
    Product2Feed
    ProductEntitlementTemplate
    Profile
    ProfileSkill
    ProfileSkillEndorsement
    ProfileSkillEndorsementFeed
    ProfileSkillEndorsementHistory
    ProfileSkillFeed
    ProfileSkillHistory
    ProfileSkillShare
    ProfileSkillUser
    ProfileSkillUserFeed
    ProfileSkillUserHistory
    PushTopic
    QuantityForecast
    QuantityForecastHistory
    Question
    QuestionDataCategorySelection
    QuestionReportAbuse
    QuestionSubscription
    QueueSobject
    Quote
    QuoteDocument
    QuoteLineItem
    RecentlyViewed
    RecordType
    RecordTypeLocalization
    Reply
    ReplyReportAbuse
    Report
    ReportFeed
    ReportTag
    ReputationLevel
    ReputationLevelLocalization
    ReputationPointsRule
    RevenueForecast
    RevenueForecastHistory
    RuleTerritory2Association
    SamlSsoConfig
    SearchPromotionRule
    SecureAgent
    SecureAgentsCluster
    Scontrol
    ScontrolLocalization
    SelfServiceUser
    ServiceContract
    ServiceContractFeed
    ServiceContractHistory
    ServiceContractOwnerSharingRule
    ServiceContractShare
    SetupEntityAccess
    SignupRequest
    Site
    SiteHistory
    SlaProcess
    Solution
    SolutionFeed
    SolutionHistory
    SolutionStatus
    SolutionTag
    StaticResource
    StreamingChannel
    TagDefinition
    Task
    TaskFeed
    TaskPriority
    TaskRelation
    TaskStatus
    TaskTag
    TaskWhoRelation
    Territory
    Territory2
    Territory2Model
    Territory2ModelHistory
    Territory2Type
    TestSuiteMembership
    ThirdPartyAccountLink
    Topic
    TopicAssignment
    TopicFeed
    TopicLocalization
    TwoFactorInfo
    UndecidedEventRelation
    User
    UserAccountTeamMember
    UserAppMenuCustomization
    UserAppMenuCustomizationShare
    UserAppMenuItem
    UserConfigTransferButton
    UserConfigTransferSkill
    UserFeed
    UserLicense
    UserLogin
    UserMembershipSharingRule
    UserPackageLicense
    UserPreference
    UserProfile
    UserProfileFeed
    UserProvAccount
    UserProvAccountStaging
    UserProvMockTarget
    UserProvisioningConfig
    UserProvisioningLog
    UserProvisioningRequest
    UserProvisioningRequestOwnerSharingRule
    UserProvisioningRequestShare
    UserRecordAccess
    UserRole
    UserShare
    UserTeamMember
    UserTerritory
    UserTerritory2Association
    VerificationHistory
    Vote
    WebLink
    WebLinkLocalization
    WorkAccess
    WorkAccessShare
    WorkBadge
    WorkBadgeDefinition
    WorkBadgeDefinitionHistory
    WorkBadgeDefinitionShare
    WorkCoaching
    WorkCoachingFeed
    WorkCoachingHistory
    WorkCoachingShare
    WorkFeedback
    WorkFeedbackHistory
    WorkFeedbackQuestion
    WorkFeedbackQuestionHistory
    WorkFeedbackQuestionSet
    WorkFeedbackQuestionSetHistory
    WorkFeedbackQuestionSetShare
    WorkFeedbackQuestionShare
    WorkFeedbackRequest
    WorkFeedbackRequestFeed
    WorkFeedbackRequestHistory
    WorkFeedbackRequestShare
    WorkFeedbackShare
    WorkGoal
    WorkGoalCollaborator
    WorkGoalCollaboratorHistory
    WorkGoalFeed
    WorkGoalHistory
    WorkGoalLink
    WorkGoalShare
    WorkOrder
    WorkOrderLineItem
    WorkPerformanceCycle
    WorkPerformanceCycleFeed
    WorkPerformanceCycleHistory
    WorkPerformanceCycleShare
    WorkReward
    WorkRewardFund
    WorkRewardFundHistory
    WorkRewardFundShare
    WorkRewardFundType
    WorkRewardFundTypeHistory
    WorkRewardFundTypeShare
    WorkRewardHistory
    WorkRewardShare
    WorkThanks
    WorkThanksShare
  ]
end
